spring:
  application:
    name: spring-event

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true

  #JPA ??
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate ??? ?? data.sql ??

  #Redis ??
  data:
    redis:
      host: localhost
      port: 6379
